version: '3'

services:
  azure:
    build:
      context: ./
      dockerfile: Dockerfile.azure
      args:
        AZURITE_VERSION: 3.17.0
    restart: on-failure
    ports:
      - 10000:10000
  
  gcs:
    build:
      context: ./
      dockerfile: Dockerfile.gcs
    ports:
      - 4443:4443 
    #command: bash -c "python init_gcs.py & gcp-storage-emulator start --host=localhost --port=9023 --in-memory --default-bucket=golden"
    command: sh -c "python init_gcs.py & /bin/fake-gcs-server -scheme http -public-host localhost:4443"
