version: '3'

services:
  azure:
    build:
      context: ./
      dockerfile: Dockerfile.azure
      args:
        AZURITE_VERSION: 3.17.0
    restart: on-failure
    ports:
      - 10000:10000
  
  gcs:
    build:
      context: ./
      dockerfile: Dockerfile.gcs
    ports:
      - 4443:4443 
    command: sh -c "python init_gcs.py & /bin/fake-gcs-server -scheme http -public-host localhost:4443"

  aws:
    build:
      context: ./
      dockerfile: Dockerfile.aws
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=s3
      - DEBUG=0 
      - START_WEB=0 
      - LAMBDA_REMOTE_DOCKER=0
      - DEFAULT_REGION=us-east-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
